Added Hoppers to Stashfinder
kami-blue/client pull request #1457
Opened 2020-10-09 23:26 UTC by widdwecat

I hope this works

Hey, it's me again. Again, I am just adding something simple.

2020-10-09 23:28 UTC, l1ving requested changes

2020-10-09 23:28 UTC, l1ving commented on src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
> +    private val hopperDensity = register(Settings.integerBuilder("MinHoppers").withMinimum(1).withMaximum(20).withValue(5).withVisibility { logDispensers.value }.build())
you forgot to change the visibility

2020-10-10 00:05 UTC, widdwecat commented on src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
> +    private val hopperDensity = register(Settings.integerBuilder("MinHoppers").withMinimum(1).withMaximum(20).withValue(5).withVisibility { logDispensers.value }.build())
sorry, I'll change that now.

2020-10-10 00:34 UTC, l1ving requested changes
You're also missing hoppers inside `add()`

2020-10-10 00:34 UTC, l1ving commented on src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
> +            return "($chests chests, $shulkers shulkers, $droppers droppers, $dispensers dispensers, $hoppers hoppers)"
you forgot to make a variable for hoppers

2020-10-10 00:34 UTC, l1ving commented on src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
> +        if (chunkStats.chests >= chestDensity.value || chunkStats.shulkers >= shulkerDensity.value || chunkStats.droppers >= dropperDensity.value || chunkStats.dispensers >= dispenserDensity.value ||
see above

2020-10-10 00:34 UTC, l1ving commented on src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
>      private data class ChunkStats(var chests: Int = 0, var shulkers: Int = 0, var droppers: Int = 0, var dispensers: Int = 0, var hot: Boolean = false) {
you're missing hoppers

2020-10-10 00:42 UTC, widdwecat commented on src/main/java/me/zeroeightsix/kami/module/modules/misc/StashFinder.kt
>      private data class ChunkStats(var chests: Int = 0, var shulkers: Int = 0, var droppers: Int = 0, var dispensers: Int = 0, var hot: Boolean = false) {
I just added it

2020-10-10 00:46 UTC, l1ving approved these changes
Thanks

2020-10-10 00:50 UTC, merged