[cleanup] Switch to OkHttp from dumb http libraries
kami-blue/client pull request #1884
Opened 2021-01-27 23:55 UTC by l1ving

Signed-off-by: lv <~@l1v.in>

2021-01-27 23:59 UTC, l1ving commented
Tested with shrunk jar in non-dev, works
![image](https://user-images.githubusercontent.com/17222512/106070097-cc7b5c00-60d1-11eb-9831-10d85848d207.png)

2021-01-28 00:00 UTC, Xiaro requested changes

2021-01-28 00:02 UTC, l1ving commented on src/main/java/me/zeroeightsix/kami/KamiMod.java
> +    public static OkHttpClient httpClient = new OkHttpClient();
Why do I need a getter? I just want one instance of the client to use

2021-01-28 01:17 UTC, Xiaro commented on src/main/java/me/zeroeightsix/kami/KamiMod.java
> +    public static OkHttpClient httpClient = new OkHttpClient();
You are writing in Java not Kotlin

2021-02-01 18:29 UTC, l1ving commented
Merging, can change it later if wanted

2021-02-01 18:30 UTC, merged