[enhancement] add binds to gui elements.
kami-blue/client pull request #1939
Opened 2021-02-15 18:19 UTC by scorbett123

Adds key binds to gui elements.

2021-02-16 00:34 UTC, Xiaro requested changes

2021-02-16 00:34 UTC, Xiaro commented on src/main/kotlin/org/kamiblue/client/gui/hudgui/HudElement.kt
> +    val bind = setting("Bind", Bind())
You can use delegation `by` here since you don't need to access anything in the `BindSetting`

2021-02-16 21:03 UTC, Xiaro approved these changes

2021-02-16 21:49 UTC, merged

2021-02-16 21:49 UTC, Xiaro commented
Thanks

2021-02-17 08:48 UTC, scorbett123 commented
Thanks