fix light based chunk bans
kami-blue/client pull request #2196
Opened 2021-04-10 18:52 UTC by czho

**Describe the pull**
quick fix for skylight lag

**Describe how this pull is helpful**
It fixes skylight no render not working on the ban machines

2021-04-10 19:54 UTC, l1ving requested changes
This should be configurable.

2021-04-11 01:11 UTC, l1ving commented
Well it doesn't look like you've enabled permission for me to push to your pull request, you'll have to do it yourself if you want it merged.

![image0](https://i.l1v.in/i/·.⋮…‥˙⋱.png)

Ideally you should have a method like so, in NoRender

```kotlin
    fun handleLighting(lightType: EnumSkyBlock): Boolean {
        return isEnabled && (skylight && lightType == EnumSkyBlock.SKY || allLightingUpdates)
    }
```

2021-04-11 02:50 UTC, czho commented
> Well it doesn't look like you've enabled permission for me to push to your pull request, you'll have to do it yourself if you want it merged.
> 
> ![image0](https://camo.githubusercontent.com/73864baabbc635fbe772c488f8b69cf9b3dfb6d872242b178d8270405c37b6b8/68747470733a2f2f692e6c31762e696e2f692f2543322542372e2545322538422541452545322538302541362545322538302541352543422539392545322538422542312e706e67)
> 
> Ideally you should have a method like so, in NoRender
> 
> ```kotlin
>     fun handleLighting(lightType: EnumSkyBlock): Boolean {
>         return isEnabled && (skylight && lightType == EnumSkyBlock.SKY || allLightingUpdates)
>     }
> ```

If you wana merge ur current changes you can, I fixed the permission thing but if not I will do the changes you asked.

2021-04-11 04:08 UTC, l1ving approved these changes

2021-04-11 04:09 UTC, merged